# Generated by Django 2.2.1 on 2022-02-10 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoreaction',
            name='send_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todoreaction',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction', to='home.Todo'),
        ),
        migrations.AddField(
            model_name='todocate',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_cate', to='setting.Home'),
        ),
        migrations.AddField(
            model_name='todo',
            name='cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo', to='home.TodoCate'),
        ),
        migrations.AddField(
            model_name='todo',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='setting.Home'),
        ),
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livingrule',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='living_rule', to='home.LivingRuleCate'),
        ),
        migrations.AddField(
            model_name='livingrule',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='living_rule', to='setting.Home'),
        ),
        migrations.AddField(
            model_name='guidelineq',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna', to='home.GuidelineQCate'),
        ),
        migrations.AddField(
            model_name='guidelinea',
            name='guideline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_cate', to='home.Guideline'),
        ),
        migrations.AddField(
            model_name='guidelinea',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='home.GuidelineQ'),
        ),
        migrations.AddField(
            model_name='guideline',
            name='home',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guideline', to='setting.Home'),
        ),
    ]
