# Generated by Django 4.0.2 on 2022-02-09 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_todo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoreaction',
            name='emoji',
        ),
        migrations.AddField(
            model_name='todo',
            name='is_done_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='is_postpone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority_num',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
