# Generated by Django 4.0.2 on 2022-02-14 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_home_is_rent_alter_home_rent_date_and_more'),
        ('home', '0004_alter_todo_priority_alter_todopriority_priority_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='livingrulecate',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='living_rule_cate', to='setting.home'),
        ),
        migrations.AlterField(
            model_name='livingrule',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='living_rule', to='setting.home'),
        ),
    ]
