# Generated by Django 4.0.2 on 2022-02-16 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_livingrulecate_home_alter_livingrule_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='livingrule',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livingrulecate',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='todo', to='home.todopriority'),
        ),
    ]
