# Generated by Django 4.0.2 on 2022-02-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_todo_is_not_done_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidelinea',
            name='guideline',
        ),
        migrations.RemoveField(
            model_name='guidelinea',
            name='question',
        ),
        migrations.RemoveField(
            model_name='guidelineq',
            name='cate',
        ),
        migrations.AddField(
            model_name='livingrule',
            name='is_guideline',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Guideline',
        ),
        migrations.DeleteModel(
            name='GuidelineA',
        ),
        migrations.DeleteModel(
            name='GuidelineQ',
        ),
        migrations.DeleteModel(
            name='GuidelineQCate',
        ),
    ]
