# Generated by Django 4.0.1 on 2022-02-19 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_guidelinea_guideline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livingrule',
            name='cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='living_rule', to='home.livingrulecate'),
        ),
    ]
