# Generated by Django 3.2.12 on 2022-02-20 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='todo', to='home.todopriority'),
        ),
    ]
