# Generated by Django 4.0.2 on 2022-02-07 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='rent_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='livein',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livein',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utility',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utility',
            name='home',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='utility', to='setting.home'),
        ),
        migrations.AlterField(
            model_name='utility',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
