# Generated by Django 4.0.2 on 2022-02-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_alter_livein_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='is_rent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='rent_date',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='rent_month',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
