# Generated by Django 4.0.2 on 2022-02-07 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_alter_livein_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.home'),
        ),
        migrations.AlterField(
            model_name='livein',
            name='home',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setting.home'),
        ),
    ]
