# Generated by Django 4.0.2 on 2022-02-16 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setting', '0003_home_is_rent_alter_home_rent_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livein',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livein',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PreRoommates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.livein')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
