# Generated by Django 4.0.2 on 2022-02-17 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setting', '0004_alter_livein_end_date_alter_livein_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='invite_link',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='receive_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Knock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('knock_at', models.DateTimeField(auto_now=True)),
                ('receive_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.home')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
