# Generated by Django 4.0.2 on 2022-02-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_alter_invite_home_alter_livein_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='rent_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utility',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
