# Generated by Django 4.0.2 on 2022-02-10 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_home_rent_month_utility_month_alter_home_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livein',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.home'),
        ),
    ]
