# Generated by Django 4.0.1 on 2022-02-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_user_nick_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='title_num',
        ),
        migrations.AddField(
            model_name='title',
            name='is_selected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
